-- Populate passwords for testing GUI purposes

INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Google', 'test', 'test', 'test1', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('YouTube', 'test', 'test', 'test2', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('X', 'test', 'test', 'test3', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Facebook', 'test', 'test', 'test4', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Instagram', 'test', 'test', 'test5', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('WhatsApp', 'test', 'test', 'test6', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Wikipedia', 'test', 'test', 'test7', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Yahoo', 'test', 'test', 'test8', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Reddit', 'test', 'test', 'test9', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Allegro', 'test', 'test', 'test10', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Amazon', 'test', 'test', 'test11', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Yandex', 'test', 'test', 'test12', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Baidu', 'test', 'test', 'test13', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('ChatGPT', 'test', 'test', 'test14', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('TikTok', 'test', 'test', 'test15', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Netflix', 'test', 'test', 'test16', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('LinkedIn', 'test', 'test', 'test17', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Outlook', 'test', 'test', 'test18', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Twitter', 'test', 'test', 'test19', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Bing', 'test', 'test', 'test20', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('Twitch', 'test', 'test', 'test21', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));
INSERT INTO passwords (service_name, username, "password", initial_vector, created_at, updated_at) VALUES ('eBay', 'test', 'test', 'test22', strftime('%Y-%m-%d %H:%M:%S', datetime('now')), strftime('%Y-%m-%d %H:%M:%S', datetime('now')));